### ISSUE TITLE
BOJ Q14888 연산자 - 넘겨주는 sum 값의 차이

### ISSUE THREAD

**Issue by gmlwjd9405** [Do-Hee/algorithm-study#140]
[Q14888 연산자](https://www.acmicpc.net/problem/14888) 넘겨주는 sum 값의 연속 계산 이해하기 

//				int result = 0; // 연산의 결과 
				switch (operators[i]) {
				case 0: // +
//					result = sum + nums[depth + 1];
					sum += nums[depth + 1];
					break;
				case 1: // -
//					result = sum - nums[depth + 1];
					sum -= nums[depth + 1];
					break;
				case 2: // *
//					result = sum * nums[depth + 1];
					sum *= nums[depth + 1];
					break;
				case 3: // /
//					result = sum / nums[depth + 1];
					sum /= nums[depth + 1];
					break;
				}
				dfs(depth + 1, sum);

**Comment by gmlwjd9405** [comment]
1. sum += nums[depth + 1]; 식으로 하면 
넘어가는 매개변수 sum에 이전의 계산값이 저장되므로, 백트래킹 할 때 문제가 발생한다.
1) + x 순서
3 + 4 -> sum = 7 저장 
7 x 5 -> sum = 35
--백트래킹 --
2) x + 순서
7 x 4 -> 문제!!

2. result = sum + nums[depth + 1]; 식으로 하면 
연산자의 선택 순서에 상관없이 넘어온 sum의 값은 유지가 되므로 올바른 결과값이 나온다.
1) + x 순서
3 + 4 -> 처음 sum은 nums[0] 저장,  매개변수로 7이 넘어감 
7 x 5  -> 처음 sum은 nums[0] 저장,  매개변수로 35이 넘어감 
--백트래킹 --
2) x + 순서
3 x 4 ->  처음 sum은 nums[0]으로 유지

**Comment by doooyeon** [comment]
👍
